import type { Metadata } from 'next';
import Link from 'next/link';
import './globals.css';

export const metadata:Metadata={title:{default:'NEPKITS HUB | Football Jerseys & Sportswear',template:'%s | NEPKITS HUB'},description:'Premium football jerseys, kits and sportswear from NEPKITS HUB.'};

function Header(){return <><div className='store-topline'>NEPKITS HUB · FOOTBALL CULTURE · PREMIUM SPORTSWEAR</div><header className='store-header'><div className='nav-shell'><Link href='/' className='brand-image'><img src='/nepkits-logo.webp' alt='NEPKITS HUB'/></Link><nav className='site-nav'><Link href='/shop'>SHOP</Link><Link href='/shop?collection=new'>NEW ARRIVALS</Link><Link href='/shop?collection=jerseys'>JERSEYS</Link><Link href='/shop?collection=kits'>KITS</Link><Link href='/shop?collection=retro'>RETRO</Link><Link href='/shop?collection=sale' className='sale-nav'>SALE</Link></nav><div className='nav-tools'><Link href='/shop'>SEARCH</Link><Link href='/wishlist'>WISHLIST</Link><Link href='/account'>ACCOUNT</Link><Link href='/cart' className='bag-link'>BAG</Link></div></div></header></>}

function Footer(){return <footer className='store-footer'><div className='footer-shell'><div className='footer-brand'><img src='/nepkits-logo.webp' alt='NEPKITS HUB'/><p>Football jerseys, kits and sportswear for people who live the game.</p></div><div><h4>SHOP</h4><Link href='/shop'>All products</Link><Link href='/shop?collection=new'>New arrivals</Link><Link href='/shop?collection=sale'>Sale</Link></div><div><h4>ACCOUNT</h4><Link href='/account'>Profile</Link><Link href='/orders'>Orders</Link><Link href='/cart'>Bag</Link><Link href='/support'>Support</Link></div><div><h4>NEPKITS HUB</h4><span>Premium football culture. Built for matchday.</span><span>COD and eSewa flows available where configured.</span></div></div><div className='footer-bottom'><span>© 2026 NEPKITS HUB</span><span>Built for the game.</span></div></footer>}

export default function RootLayout({children}:{children:React.ReactNode}){return <html lang='en'><body><Header/>{children}<Footer/></body></html>}