'use client';
import Link from 'next/link';
import { useEffect,useMemo,useState } from 'react';
import { ArrowUpRight,ChevronRight,Play } from 'lucide-react';
import { supabase } from '@/lib/supabase-browser';
import { ProductCard } from '@/components/product-card';
import { imageFor } from '@/lib/store-utils';

export default function Home(){
 const [products,setProducts]=useState<any[]>([]);const [categories,setCategories]=useState<any[]>([]);const [banner,setBanner]=useState<any>(null);const [settings,setSettings]=useState<any>(null);
 useEffect(()=>{(async()=>{const [p,c,b,s]=await Promise.all([supabase.from('products').select('*,category:categories(name,slug),images:product_images(url,is_primary,sort_order),sizes:product_sizes(id,size,stock_qty,sort_order)').eq('published',true).order('featured',{ascending:false}).order('created_at',{ascending:false}),supabase.from('categories').select('*').eq('is_active',true).order('sort_order'),supabase.from('homepage_banners').select('*').eq('active',true).order('sort_order').limit(1).maybeSingle(),supabase.from('store_settings').select('*').limit(1).maybeSingle()]);setProducts(p.data??[]);setCategories(c.data??[]);setBanner(b.data);setSettings(s.data)})()},[]);
 const latest=products.filter(p=>p.new_arrival);const featured=products.filter(p=>p.featured);const best=[...products].sort((a,b)=>Number(b.sold_count||0)-Number(a.sold_count||0));const sale=products.filter(p=>Number(p.discount_percent||0)>0);const hero=banner?.image_url||imageFor(featured[0]||products[0]);
 const collectionImages=useMemo(()=>categories.slice(0,5).map(c=>({...c,product:products.find(p=>p.category_id===c.id)})),[categories,products]);
 return <main className='new-home'>
  <section className='home-hero'><img src={hero} alt='NEPKITS HUB campaign'/><div className='hero-shade'/><div className='home-hero-content'><div className='hero-side-label'>NK / 2026 COLLECTION</div><div className='hero-center'><p className='eyebrow-light'>{banner?.title||'FOOTBALL CULTURE'}</p><h1>THE SHIRT<br/><span>IS THE SIGNAL.</span></h1><p>{banner?.subtitle||settings?.tagline||'Premium jerseys, kits and sportswear made for matchday and beyond.'}</p><div className='hero-buttons'><Link href='/shop' className='red-button'>SHOP THE COLLECTION <ArrowUpRight size={16}/></Link><Link href='/shop?collection=new' className='outline-button'>NEW ARRIVALS</Link></div></div><div className='hero-scroll'>SCROLL TO EXPLORE <ChevronRight size={14}/></div></div></section>
  <div className='marquee-band'><div>NEPKITS HUB</div><div>FOOTBALL CULTURE</div><div>JERSEYS</div><div>KITS</div><div>TRAINING</div><div>RETRO</div><div>NEPKITS HUB</div></div>
  <section className='home-section dark-section'><div className='wide-shell'><div className='section-header-white'><div><span>01 / COLLECTIONS</span><h2>FIND YOUR<br/><em>COLOURWAY.</em></h2></div><Link href='/shop'>VIEW ALL <ArrowUpRight size={15}/></Link></div><div className='collection-rail'>{collectionImages.map((c,i)=><Link className={'collection-tile tile-'+i} key={c.id} href={'/shop?category='+c.id}><img src={imageFor(c.product)} alt={c.name}/><div className='collection-tile-shade'/><div className='collection-tile-copy'><small>{String(i+1).padStart(2,'0')} / COLLECTION</small><strong>{c.name}</strong><span>{c.description||'Explore collection'} <ArrowUpRight size={13}/></span></div></Link>)}</div></div></section>
  <section className='home-section paper-section'><div className='wide-shell'><div className='feature-bento'><div className='feature-copy'><span className='section-number'>02 / THE LATEST DROP</span><h2>BUILT FOR<br/><strong>MATCHDAY.</strong></h2><p>Our latest football edit brings together new arrivals, fan favourites and the pieces that keep the game going after the final whistle.</p><Link href='/shop?collection=new' className='dark-button'>EXPLORE THE DROP <ArrowUpRight size={15}/></Link></div><div className='feature-image tall'><img src={imageFor(latest[0]||featured[0]||products[0])} alt='Latest drop'/><div className='feature-caption'>NK / LATEST DROP</div></div><div className='feature-image'><img src={imageFor(best[1]||best[0]||products[1])} alt='Fan favourite'/><div className='feature-caption'>FAN FAVOURITE</div></div></div></div></section>
  <section className='home-section paper-section pt0'><div className='wide-shell'><div className='section-header-dark'><div><span>03 / NEW ARRIVALS</span><h2>JUST <em>LANDED.</em></h2></div><Link href='/shop?collection=new'>SHOP NEW <ArrowUpRight size={15}/></Link></div><div className='home-products'>{(latest.length?latest:featured).slice(0,4).map(p=><ProductCard key={p.id} product={p}/>)}</div></div></section>
  <section className='split-statement'><div className='split-art'><img src={imageFor(best[0]||products[0])} alt='NEPKITS football culture'/><div className='art-play'><Play size={18}/></div></div><div className='split-copy'><span>04 / THE NEPKITS CODE</span><h2>NOT<br/><em>JUST</em><br/>A JERSEY.</h2><p>Wear the badge. Carry the culture. The collection is designed around football as identity, ritual and everyday style.</p><Link href='/shop' className='white-line-button'>SHOP ALL PRODUCTS <ArrowUpRight size={15}/></Link></div></section>
  <section className='home-section dark-section sale-home'><div className='wide-shell'><div className='section-header-white'><div><span>05 / LIMITED EDIT</span><h2>RED TAG<br/><em>SEASON.</em></h2></div><Link href='/shop?collection=sale'>SHOP SALE <ArrowUpRight size={15}/></Link></div><div className='home-products'>{sale.slice(0,4).map(p=><ProductCard key={p.id} product={p}/>)}</div></div></section>
  <section className='signup-strip'><div className='wide-shell signup-inner'><div><span>06 / STAY IN THE LOOP</span><h2>FIRST LOOKS.<br/><em>NOISE OFF.</em></h2></div><form onSubmit={e=>e.preventDefault()}><input placeholder='Your email address'/><button>JOIN <ArrowUpRight size={16}/></button></form></div></section>
 </main>
}