'use client';
import { useEffect,useMemo,useState } from 'react';
import { SlidersHorizontal,Search,ChevronDown } from 'lucide-react';
import { supabase } from '@/lib/supabase-browser';
import { ProductCard } from '@/components/product-card';
export default function Shop(){
 const [products,setProducts]=useState<any[]>([]);const [categories,setCategories]=useState<any[]>([]);const [q,setQ]=useState('');const [category,setCategory]=useState('');const [sort,setSort]=useState('featured');const [mobileFilters,setMobileFilters]=useState(false);
 useEffect(()=>{(async()=>{const [p,c]=await Promise.all([supabase.from('products').select('*,category:categories(name,slug),images:product_images(url,is_primary,sort_order),sizes:product_sizes(id,size,stock_qty,sort_order)').eq('published',true),supabase.from('categories').select('*').eq('is_active',true).order('sort_order')]);setProducts(p.data??[]);setCategories(c.data??[])})()},[]);
 const filtered=useMemo(()=>{let list=[...products].filter(p=>(!q||[p.name,p.team,p.player,p.season,p.league].filter(Boolean).join(' ').toLowerCase().includes(q.toLowerCase()))&&(!category||p.category_id===category));if(sort==='newest')list.sort((a,b)=>+new Date(b.created_at)-+new Date(a.created_at));if(sort==='price-low')list.sort((a,b)=>Number(a.price)-Number(b.price));if(sort==='price-high')list.sort((a,b)=>Number(b.price)-Number(a.price));if(sort==='popular')list.sort((a,b)=>Number(b.sold_count||0)-Number(a.sold_count||0));return list},[products,q,category,sort]);
 return <main className='catalog-page'><div className='wide-shell'><div className='catalog-top'><div><span>SHOP / NEPKITS HUB</span><h1>THE<br/><em>COLLECTION.</em></h1></div><p>Football shirts, kits, retro pieces and training wear from the live NEPKITS HUB catalog.</p></div><div className='catalog-tools'><div className='search-box'><Search size={16}/><input placeholder='Search team, player, season…' value={q} onChange={e=>setQ(e.target.value)}/></div><button className='filter-mobile' onClick={()=>setMobileFilters(!mobileFilters)}><SlidersHorizontal size={15}/>FILTERS</button><select value={sort} onChange={e=>setSort(e.target.value)}><option value='featured'>Featured</option><option value='newest'>Newest</option><option value='popular'>Popular</option><option value='price-low'>Price Low → High</option><option value='price-high'>Price High → Low</option></select></div><div className='catalog-layout'><aside className={mobileFilters?'filters open':'filters'}><div className='filter-title'>CATEGORIES <ChevronDown size={14}/></div><button className={!category?'active':''} onClick={()=>setCategory('')}>All products</button>{categories.map(c=><button key={c.id} className={category===c.id?'active':''} onClick={()=>setCategory(c.id)}>{c.name}</button>)}<div className='filter-divider'/><div className='filter-title'>COLLECTION</div><button onClick={()=>setCategory('')}>New arrivals</button><button onClick={()=>setCategory('')}>Best sellers</button><button onClick={()=>setCategory('')}>Sale</button></aside><section className='catalog-results'><div className='results-meta'><span>{filtered.length} products</span><span>Live catalog</span></div>{filtered.length?<div className='catalog-grid'>{filtered.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<div className='empty-catalog'><h2>NO MATCHES.</h2><p>Try another team, player or category.</p></div>}</section></div></div></main>