'use client';
import { useEffect,useMemo,useState } from 'react';
import Link from 'next/link';
const money=(n:number|string)=>new Intl.NumberFormat('en-NP',{style:'currency',currency:'NPR',maximumFractionDigits:0}).format(Number(n));
const imageFor=(p:any)=>p?.images?.find((x:any)=>x.is_primary)?.url??p?.images?.[0]?.url??'';
function addCart(product:any,size:string){const c=JSON.parse(localStorage.getItem('nepkits-cart')||'[]');const i=c.findIndex((x:any)=>x.product.id===product.id&&x.size===size);if(i<0)c.push({product,size,quantity:1});else c[i].quantity++;localStorage.setItem('nepkits-cart',JSON.stringify(c));}
function Card({p}:{p:any}){return <article className='product-tile'><Link href={'/products/'+p.slug} className='product-photo-wrap'><img className='product-photo primary' src={imageFor(p)} alt={p.name}/><div className='product-badges'>{p.new_arrival&&<span>NEW</span>}{Number(p.discount_percent)>0&&<span>SALE</span>}</div></Link><div className='product-tile-copy'><small>{p.team||'NEPKITS'} {p.season?'· '+p.season:''}</small><h3>{p.name}</h3><div className='tile-price'><strong>{money(p.price)}</strong>{p.original_price&&<del>{money(p.original_price)}</del>}<span>{Number(p.discount_percent)>0?Math.round(Number(p.discount_percent))+'% OFF':'★ '+Number(p.rating||0).toFixed(1)}</span></div><button className='quick-add' onClick={()=>addCart(p,p.sizes?.find((s:any)=>Number(s.stock_qty)>0)?.size||'M')}>+ QUICK ADD</button></div></article>}
export default function Shop(){const [ps,setPs]=useState<any[]>([]);const [cats,setCats]=useState<any[]>([]);const [q,setQ]=useState('');const [cat,setCat]=useState('');const [sort,setSort]=useState('featured');const [error,setError]=useState('');
useEffect(()=>{(async()=>{try{const res=await fetch('/api/catalog',{cache:'no-store'});const json=await res.json();if(!res.ok)throw new Error(json.error||'Catalog unavailable');setPs(json.products??[]);setCats(json.categories??[])}catch(e:any){console.error('NEPKITS catalog error',e);setError(e?.message||'Catalog unavailable')}})()},[]);
const list=useMemo(()=>{let x=ps.filter(p=>(!q||[p.name,p.team,p.player,p.season,p.league].filter(Boolean).join(' ').toLowerCase().includes(q.toLowerCase()))&&(!cat||p.category_id===cat));if(sort==='newest')x.sort((a,b)=>+new Date(b.created_at)-+new Date(a.created_at));if(sort==='popular')x.sort((a,b)=>Number(b.sold_count||0)-Number(a.sold_count||0));if(sort==='low')x.sort((a,b)=>Number(a.price)-Number(b.price));if(sort==='high')x.sort((a,b)=>Number(b.price)-Number(a.price));return x},[ps,q,cat,sort]);
return <main className='catalog-page'><div className='wide-shell'><div className='catalog-top'><div><span>SHOP / NEPKITS HUB</span><h1>THE<br/><em>COLLECTION.</em></h1></div><p>Every jersey, kit, retro shirt and training piece in the live NEPKITS HUB catalog.</p></div><div className='catalog-tools'><input className='catalog-search' placeholder='SEARCH TEAM, PLAYER, SEASON…' value={q} onChange={e=>setQ(e.target.value)}/><select value={sort} onChange={e=>setSort(e.target.value)}><option value='featured'>FEATURED</option><option value='newest'>NEWEST</option><option value='popular'>POPULAR</option><option value='low'>PRICE LOW</option><option value='high'>PRICE HIGH</option></select></div><div className='catalog-layout'><aside className='filters'><strong>FILTER BY CATEGORY</strong><button className={!cat?'active':''} onClick={()=>setCat('')}>ALL PRODUCTS</button>{cats.map(c=><button className={cat===c.id?'active':''} key={c.id} onClick={()=>setCat(c.id)}>{c.name.toUpperCase()}</button>)}<div className='filter-divider'/><strong>COLLECTION</strong><Link href='/shop?collection=new'>NEW ARRIVALS</Link><Link href='/shop?collection=sale'>SALE</Link></aside><section className='catalog-results'><div className='results-meta'><span>{list.length} PRODUCTS</span><span>{error?'CATALOG CONNECTION ISSUE':'LIVE CATALOG'}</span></div><div className='catalog-grid'>{list.map(p=><Card key={p.id} p={p}/>)}</div></section></div></div></main>}